# Generated by Django 5.1.7 on 2025-04-10 07:44

import django.db.models.deletion
import productmodule.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_paths',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=productmodule.models.product_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='productmodule.product')),
            ],
        ),
    ]
