# Generated by Django 5.1.7 on 2025-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodule', '0002_remove_product_image_paths_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/product_images/'),
        ),
    ]
